[build]
  [build]
  command = "NODE_OPTIONS=--openssl-legacy-provider npm run build"
  publish = "build"
  node_version = "16"  # Ensure Node.js 16.x is used

[build.environment]
  NODE_ENV = "production"
